apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-deploy-nginx-kustomization
  namespace: flux-cd
spec:
  interval: 5s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-deploy-nginx
  targetNamespace: default
