apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-deploy-nginx 
  namespace: flux-cd
spec:
  interval: 5s
  ref:
    branch: main
  url: https://github.com/qiaodeli111/flux-cd.git
