apiVersion: v1
kind: Namespace
metadata:
  name: flux-cd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: flux-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.26.2
        name: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
